### ISSUE TITLE
Error when installing palantir plugin in Intellij 2024.1.1

### ISSUE THREAD

**Issue by mrksph** [palantir/palantir-java-format#1087]
## What happened?

After updating to IntelliJ 2024.1 (and then to 2024.1.1) I can't update palantir-java-format. I also tried to reinstall the plugin but still get the same error.

I double checked because it could be a HTTP Proxy error but it is correctly configured.  Also asked a work colleague to check if they get the same error, and yes the same behaviour when installing palantir-java-format but no issues installing other plugins.

I tried to install other plugins and they install correctly with no issues.

## What did you want to happen?

I want to be able to install the plugin in IntelliJ 2024.1 +

![image](https://github.com/palantir/palantir-java-format/assets/10486135/6a67bb41-cac5-4f64-9d4b-d545df891afa)

Some logs from IntelliJ

> 2024-05-13 12:21:00,723 [  68015]   INFO - #c.i.i.p.m.MarketplaceRequests - Cannot load data from https://plugins.jetbrains.com/api/icon?pluginId=io.flutter&theme=DARCULA (statusCode=403)
2024-05-13 12:21:00,726 [  68018]   FINE - #c.i.u.i.HttpRequests - response from https://downloads.marketplace.jetbrains.com/files/icons/intellij/com.intellij.zh/darcula.svg: 403
2024-05-13 12:21:00,727 [  68019]   INFO - #c.i.i.p.m.MarketplaceRequests - Cannot load data from https://plugins.jetbrains.com/api/icon?pluginId=com.intellij.zh&theme=DARCULA (statusCode=403)
2024-05-13 12:21:00,826 [  68118]   FINE - #c.i.u.i.HttpRequests - response from https://downloads.marketplace.jetbrains.com/files/icons/intellij/com.jetbrains.php.phpspec/darcula.svg: 403
2024-05-13 12:21:00,828 [  68120]   INFO - #c.i.i.p.m.MarketplaceRequests - Cannot load data from https://plugins.jetbrains.com/api/icon?pluginId=com.jetbrains.php.phpspec&theme=DARCULA (statusCode=403)
2024-05-13 12:21:00,882 [  68174]   FINE - #c.i.u.i.HttpRequests - response from https://downloads.marketplace.jetbrains.com/files/icons/intellij/com.intellij.aqua/darcula.svg: 403
2024-05-13 12:21:00,883 [  68175]   INFO - #c.i.i.p.m.MarketplaceRequests - Cannot load data from https://plugins.jetbrains.com/api/icon?pluginId=com.intellij.aqua&theme=DARCULA (statusCode=403)
2024-05-13 12:21:00,996 [  68288]   FINE - #c.i.u.i.HttpRequests - response from https://downloads.marketplace.jetbrains.com/files/icons/intellij/com.pestphp.pest_intellij/darcula.svg: 403
2024-05-13 12:21:00,997 [  68289]   INFO - #c.i.i.p.m.MarketplaceRequests - Cannot load data from https://plugins.jetbrains.com/api/icon?pluginId=com.pestphp.pest-intellij&theme=DARCULA (statusCode=403)
2024-05-13 12:21:01,099 [  68391]   FINE - #c.i.u.i.HttpRequests - response from https://downloads.marketplace.jetbrains.com/files/icons/intellij/io.artage.sfcc.salesforce_commerce_cloud/darcula.svg: 403
2024-05-13 12:21:01,100 [  68392]   INFO - #c.i.i.p.m.MarketplaceRequests - Cannot load data from https://plugins.jetbrains.com/api/icon?pluginId=io.artage.sfcc.salesforce-commerce-cloud&theme=DARCULA (statusCode=403)
2024-05-13 12:21:01,249 [  68541]   FINE - #c.i.u.i.HttpRequests - response from https://downloads.marketplace.jetbrains.com/files/icons/intellij/mobi.hsz.idea.gitignore/darcula.svg: 304
2024-05-13 12:21:01,426 [  68718]   FINE - #c.i.u.i.HttpRequests - response from https://downloads.marketplace.jetbrains.com/files/icons/intellij/org.jetbrains.plugins.vue/darcula.svg: 403
2024-05-13 12:21:01,427 [  68719]   INFO - #c.i.i.p.m.MarketplaceRequests - Cannot load data from https://plugins.jetbrains.com/api/icon?pluginId=org.jetbrains.plugins.vue&theme=DARCULA (statusCode=403)
2024-05-13 12:21:01,831 [  69123]   FINE - #c.i.u.i.HttpRequests - response from https://downloads.marketplace.jetbrains.com/files/icons/intellij/dart/darcula.svg: 403
2024-05-13 12:21:01,832 [  69124]   INFO - #c.i.i.p.m.MarketplaceRequests - Cannot load data from https://plugins.jetbrains.com/api/icon?pluginId=Dart&theme=DARCULA (statusCode=403)
2024-05-13 12:21:20,804 [  88096]   INFO - #c.i.o.u.i.PluginDownloader - Cannot download '[https://downloads.marketplace.jetbrains.com/files/13180/531366/palantir-java-format-2.46.0.zip?updateId=531366&pluginId=13180&family=INTELLIJ&uuid=1904241e5d9584f-fc97-45ba-94d6-c922034f0549&updatedFrom=&code=IU&build=241.14494.240':](https://downloads.marketplace.jetbrains.com/files/13180/531366/palantir-java-format-2.46.0.zip?updateId=531366&pluginId=13180&family=INTELLIJ&uuid=1904241e5d9584f-fc97-45ba-94d6-c922034f0549&updatedFrom=&code=IU&build=241.14494.240%27:) Connection closed at byte 2765312. Expected 13001640 bytes.
, response: 200 OK
java.io.IOException: Cannot download '[https://downloads.marketplace.jetbrains.com/files/13180/531366/palantir-java-format-2.46.0.zip?updateId=531366&pluginId=13180&family=INTELLIJ&uuid=1904241e5d9584f-fc97-45ba-94d6-c922034f0549&updatedFrom=&code=IU&build=241.14494.240':](https://downloads.marketplace.jetbrains.com/files/13180/531366/palantir-java-format-2.46.0.zip?updateId=531366&pluginId=13180&family=INTELLIJ&uuid=1904241e5d9584f-fc97-45ba-94d6-c922034f0549&updatedFrom=&code=IU&build=241.14494.240%27:) Connection closed at byte 2765312. Expected 13001640 bytes.
, response: 200 OK
    at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:477)
    at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:461)
    at com.intellij.util.io.HttpRequests$Request.saveToFile(HttpRequests.java:94)
    at com.intellij.ide.plugins.marketplace.MarketplacePluginDownloadService.downloadPlugin$lambda$0(MarketplacePluginDownloadService.kt:74)
    at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:529)
    at com.intellij.util.io.HttpRequests.process(HttpRequests.java:511)
    at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:340)
    at com.intellij.ide.plugins.marketplace.MarketplacePluginDownloadService.downloadPlugin(MarketplacePluginDownloadService.kt:72)
    at com.intellij.openapi.updateSettings.impl.PluginDownloader.tryDownloadPlugin(PluginDownloader.java:360)
    at com.intellij.openapi.updateSettings.impl.PluginDownloader.prepareToInstall(PluginDownloader.java:214)
    at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:252)
    at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstallWithCallback(PluginInstallOperation.java:219)
    at com.intellij.ide.plugins.PluginInstallOperation.prepareToInstall(PluginInstallOperation.java:191)
    at com.intellij.ide.plugins.PluginInstallOperation.run(PluginInstallOperation.java:127)
    at com.intellij.ide.plugins.newui.MyPluginModel.runInstallOperation(MyPluginModel.java:494)
    at com.intellij.ide.plugins.newui.MyPluginModel$1.run(MyPluginModel.java:463)
    at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:477)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:133)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$6(CoreProgressManager.java:528)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:250)
    at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$0(ProgressManager.java:100)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:217)
    at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:660)
    at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:735)
    at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:691)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:659)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:79)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:202)
    at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:100)
    at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$5(ProgressRunner.java:250)
    at com.intellij.openapi.progress.impl.ProgressRunner$ProgressRunnable.run(ProgressRunner.java:500)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
    at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
    at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
    at java.base/java.lang.Thread.run(Thread.java:840)
Caused by: java.io.IOException: Connection closed at byte 2765312. Expected 13001640 bytes.
    at com.intellij.util.net.NetUtils.copyStreamContent(NetUtils.java:254)
    at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:470)
    ... 37 more
2024-05-13 12:21:20,805 [  88097]   INFO - #c.i.o.u.i.PluginDownloader - PluginDownloader error: Cannot download '[https://downloads.marketplace.jetbrains.com/files/13180/531366/palantir-java-format-2.46.0.zip?updateId=531366&pluginId=13180&family=INTELLIJ&uuid=1904241e5d9584f-fc97-45ba-94d6-c922034f0549&updatedFrom=&code=IU&build=241.14494.240':](https://downloads.marketplace.jetbrains.com/files/13180/531366/palantir-java-format-2.46.0.zip?updateId=531366&pluginId=13180&family=INTELLIJ&uuid=1904241e5d9584f-fc97-45ba-94d6-c922034f0549&updatedFrom=&code=IU&build=241.14494.240%27:) Connection closed at byte 2765312. Expected 13001640 bytes.
, response: 200 OK
2024-05-13 12:21:28,796 [  96088]   WARN - #c.i.o.o.e.ConfigurableCardPanel - auto-dispose 'Plugins' id=preferences.pluginManager
2024-05-13 12:21:29,112 [  96404]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-05-13 12:21:29,115 [  96407]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files
2024-05-13 12:21:29,588 [  96880]   INFO - #c.i.a.o.PathMacrosImpl - Saved path macros: {MAVEN_REPOSITORY=C:\Users\s9t6bh\.m2\repository}
2024-05-13 12:21:29,617 [  96909]   INFO - #c.i.c.ComponentStoreImpl - Saving appFileTypeManager took 12 ms, WebServers took 13 ms
2024-05-13 12:21:29,973 [  97265]   WARN - #c.i.u.x.Binding - No accessors for org.jetbrains.kotlin.cli.common.arguments.InternalArgument. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
2024-05-13 12:21:30,054 [  97346]   INFO - #c.i.c.ComponentStoreImpl - Saving Project(name=PAMOS, containerState=COMPONENT_CREATED, componentStore=C:\srdev\projects\PAMOS)ProjectDependenciesModelState took 17 ms
2024-05-13 12:21:31,513 [  98805]   WARN - #c.i.u.x.Binding - No accessors for com.intellij.toolWindow.ToolWindowLayoutStorageManagerState. This means that state class cannot be serialized properly. Please see https://jb.gg/ij-psoc
2024-05-13 12:21:33,099 [ 100391]   INFO - #c.i.u.MemTester - not supported: Windows is not supported
2024-05-13 12:21:44,793 [ 112085]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.SdkEntity to files
2024-05-13 12:21:44,794 [ 112086]   INFO - #c.i.w.i.i.j.s.JpsGlobalModelSynchronizerImpl - Saving global entities com.intellij.platform.workspace.jps.entities.LibraryEntity to files

**Comment by hantsy** [comment]
In the latest IDEA 2024.2.1, can not install it from Marketplace, the `Install` button can not be clicked.
