### ISSUE TITLE
Eclipse plugin overriden by active formatter profile configuration

### ISSUE THREAD

**Issue by lucas-mpc-brant** [palantir/palantir-java-format#1105]
## What happened?
After following installation instructions, the palantir formatter is still overriden by configurations of the standard formatter profile. Some of the palantir rules still apply, but different active profiles have visible impact on formatting.

Version: 2024-03 (4.31.0)
Build id: 20240307-1437

## What did you want to happen?
The palantir formatter implementation should ignore active profile rules (as I don't think there is a way to have NO active profile).

**Comment by beuss** [comment]
Are you sure Palantir is actually activated?
Eclipse silently fails to use it if there is an error upon plugin initialization.
* Go into Window » Show Views » Error log
* Then preferences » Java » Code Style to select palantir as formatter implement. You can have a first (silent) exception here, despite the select keeping palantir value, error log shows an error and says Eclipse falls back to built-in implementation.
You can also have an exception on formatting, same diagnosis : trigger file formatting somehow and check error log

**Comment by difflaender** [comment]
I was wondering the same thing, so thanks for pointing out the Error Log. It does indeed say that it's returning the built-in formatter due to an error.

The actual underlying error of the plugin (built from source) in my case seems to be that it cannot load the actual Palantir implementation classes despite them being bundled as libs with the dropin.
(Despite the version number from the manifest here, this was actually with version 2.68.0)
```
Caused by: java.lang.ClassNotFoundException: com.palantir.javaformat.java.FormatterException cannot be found by palantir-java-format-eclipse-plugin_2.38.0
	at org.eclipse.osgi.internal.loader.BundleLoader.generateException(BundleLoader.java:562)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass0(BundleLoader.java:557)
	at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:434)
	at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:174)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 48 more
```

However, I then went back to the 2.50.0 tag and built that instead. While I had to skip the spotlessJavaCheck task during the build, I was eventually able to get an artifact that works in Eclipse without triggering this error.
