### ISSUE TITLE
Palantir formatter throws java.lang.NoClassDefFound error

### ISSUE THREAD

**Issue by hlavki** [palantir/palantir-java-format#751]
## What happened?

If I use Palantir formatted in netbeans 14rc4 I get:

```
java.lang.NoClassDefFoundError: fj/F
	at com.palantir.javaformat.doc.HasUniqueId.ord(HasUniqueId.java:37)
	at com.palantir.javaformat.doc.State.startingState(State.java:87)
	at com.palantir.javaformat.OpsBuilder.build(OpsBuilder.java:655)
	at com.palantir.javaformat.java.Formatter.format(Formatter.java:157)
	at com.palantir.javaformat.java.Formatter.getFormatReplacements(Formatter.java:308)
	at com.palantir.javaformat.java.Formatter.formatSource(Formatter.java:284)
	at de.funfried.netbeans.plugins.external.formatter.java.palantir.PalantirJavaFormatterWrapper.format(PalantirJavaFormatterWrapper.java:78)
	at de.funfried.netbeans.plugins.external.formatter.java.palantir.PalantirFormatJob.format(PalantirFormatJob.java:63)
	at de.funfried.netbeans.plugins.external.formatter.java.base.AbstractJavaFormatterService.format(AbstractJavaFormatterService.java:49)
	at de.funfried.netbeans.plugins.external.formatter.FormatterServiceDelegate.format(FormatterServiceDelegate.java:95)
	at de.funfried.netbeans.plugins.external.formatter.ui.editor.ExternalFormatterReformatTaskFactory$2.reformat(ExternalFormatterReformatTaskFactory.java:93)
	at org.netbeans.modules.editor.indent.TaskHandler$MimeItem.runTask(TaskHandler.java:550)
	at org.netbeans.modules.editor.indent.TaskHandler.runTasks(TaskHandler.java:309)
	at org.netbeans.modules.editor.indent.IndentImpl.reformat(IndentImpl.java:349)
	at org.netbeans.modules.editor.indent.api.Reformat.reformat(Reformat.java:129)
	at org.netbeans.editor.ActionFactory$FormatAction$1$1.run(ActionFactory.java:1854)
	at org.netbeans.editor.GuardedDocument.runAtomicAsUser(GuardedDocument.java:333)
	at org.netbeans.editor.ActionFactory$FormatAction$1.run(ActionFactory.java:1833)
	at org.netbeans.modules.progress.ui.RunOffEDTImpl$1.run(RunOffEDTImpl.java:146)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1418)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:45)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:278)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
```

**Comment by hlavki** [comment]
Sorry, wrong repository ;)
