### ISSUE TITLE
IntelliJ Plugin + Java 17

### ISSUE THREAD

**Issue by nekr0s** [palantir/palantir-java-format#775]
## What happened?
1. Build the application using `gradle clean build -x test`
2. Import the IntelliJ zip plugin from /idea-plugin/build/distributions
3. Load a Java 17 project
4. Trying to format results in the following error:
```
Got unexpected exception during formatting DemoTest.java

java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error running formatter command
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ProcessingTask.checkStop(AbstractLayoutCodeProcessor.java:468)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ProcessingTask.performFileProcessing(AbstractLayoutCodeProcessor.java:462)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor.lambda$runProcessFile$0(AbstractLayoutCodeProcessor.java:291)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$2.run(AbstractLayoutCodeProcessor.java:316)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:442)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:114)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsynchronously$5(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:189)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:608)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:683)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:639)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:607)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Error running formatter command
	at com.palantir.javaformat.bootstrap.BootstrappingFormatterService.getFormatReplacements(BootstrappingFormatterService.java:58)
	at com.palantir.javaformat.intellij.PalantirCodeStyleManager.getReplacements(PalantirCodeStyleManager.java:85)
	at com.palantir.javaformat.intellij.PalantirCodeStyleManager.format(PalantirCodeStyleManager.java:198)
	at com.palantir.javaformat.intellij.PalantirCodeStyleManager.formatInternal(PalantirCodeStyleManager.java:185)
	at com.palantir.javaformat.intellij.PalantirCodeStyleManager.reformatText(PalantirCodeStyleManager.java:119)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$doReformat$5(ReformatCodeProcessor.java:196)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:147)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$doReformat$6(ReformatCodeProcessor.java:186)
	at com.intellij.openapi.editor.ex.util.EditorScrollingPositionKeeper.perform(EditorScrollingPositionKeeper.java:100)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.doReformat(ReformatCodeProcessor.java:186)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$2(ReformatCodeProcessor.java:134)
	at com.intellij.application.options.CodeStyle.doWithTemporarySettings(CodeStyle.java:338)
	at com.intellij.codeInsight.actions.ReformatCodeProcessor.lambda$prepareTask$3(ReformatCodeProcessor.java:130)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ProcessingTask.lambda$performFileProcessing$5(AbstractLayoutCodeProcessor.java:459)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$1(WriteCommandAction.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:1015)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.lambda$doRunWriteCommandAction$2(WriteCommandAction.java:148)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:219)
	at com.intellij.openapi.command.impl.CoreCommandProcessor.executeCommand(CoreCommandProcessor.java:184)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.doRunWriteCommandAction(WriteCommandAction.java:157)
	at com.intellij.openapi.command.WriteCommandAction$BuilderImpl.run(WriteCommandAction.java:124)
	at com.intellij.codeInsight.actions.AbstractLayoutCodeProcessor$ProcessingTask.lambda$performFileProcessing$6(AbstractLayoutCodeProcessor.java:459)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.LaterInvocator$1.run(LaterInvocator.java:96)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.io.IOException: Command terminated with exit value 1
Command: C:\Users\xxx\.jdks\openjdk-17.0.2\bin\java.exe --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED -cp C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\checker-qual-3.13.0.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\error_prone_annotations-2.11.0.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\failureaccess-1.0.1.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\functionaljava-4.8.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\guava-31.1-jre.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\j2objc-annotations-1.3.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\jackson-annotations-2.13.3.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\jackson-core-2.13.3.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\jackson-databind-2.13.3.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\jackson-datatype-guava-2.13.3.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\jackson-datatype-jdk8-2.13.3.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\jackson-module-parameter-names-2.13.3.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\jsr305-3.0.2.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\palantir-java-format-2.25.0-1-gd8a3116.dirty.jar;C:\Users\xxx\AppData\Roaming\JetBrains\IntelliJIdea2022.1\plugins\palantir-java-format\impl\palantir-java-format-spi-2.25.0-1-gd8a3116.dirty.jar com.palantir.javaformat.java.Main --character-ranges 0:5793 --output-replacements --palantir -
Stdout:

Stderr:
Exception in thread "main" java.lang.LinkageError: com.palantir.javaformat.java.java14.Java14InputAstVisitor
	at com.palantir.javaformat.java.Formatter.format(Formatter.java:148)
	at com.palantir.javaformat.java.Formatter.getFormatReplacements(Formatter.java:308)
	at com.palantir.javaformat.java.FormatFileCallable.formatReplacements(FormatFileCallable.java:58)
	at com.palantir.javaformat.java.FormatFileCallable.call(FormatFileCallable.java:51)
	at com.palantir.javaformat.java.Main.formatStdin(Main.java:191)
	at com.palantir.javaformat.java.Main.format(Main.java:103)
	at com.palantir.javaformat.java.Main.main(Main.java:69)
Caused by: java.lang.ClassNotFoundException: com.palantir.javaformat.java.java14.Java14InputAstVisitor
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:375)
	at com.palantir.javaformat.java.Formatter.format(Formatter.java:143)
	... 6 more

	at com.palantir.javaformat.bootstrap.FormatterCommandRunner.runWithStdin(FormatterCommandRunner.java:53)
	at com.palantir.javaformat.bootstrap.BootstrappingFormatterService.getFormatReplacementsInternal(BootstrappingFormatterService.java:83)
	at com.palantir.javaformat.bootstrap.BootstrappingFormatterService.getFormatReplacements(BootstrappingFormatterService.java:56)
	... 54 more
```
When switching the project to Java 11 the formatting works fine with no issues.

## What did you want to happen?
Format Java 17 projects.

PS: I might be doing something wrong, I wanted to try to make some changes to the source code and try them out in IntelliJ, but it seems like even without any changes (by just building it) it gives me an error when trying to format Java 17 project.
PS2: The plugin available directly from IntelliJ Marketplace seems to work also on Java 17, the problem seems to appear only if I'm building the application using `gradle clean build`.

**Comment by nekr0s** [comment]
Seems like this was an issue of how I was building the project. Upgrading my java version seems to fix the issue. Closing.
