### ISSUE TITLE
JDK 11 and local field name "sealed" cause error

### ISSUE THREAD

**Issue by slawekjaranowski** [palantir/palantir-java-format#865]
## What happened?

Test class:

```java
package org.test;

public class Test {
    void test() {
        String sealed = "a sealed test";
    }
}
```

executing: `mvn -V spotless:2.36.0:apply`

### JDK 11

```
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Java version: 11.0.18, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@11/11.0.18/libexec/openjdk.jdk/Contents/Home

...

[INFO] --- spotless:2.36.0:apply (default-cli) @ test ---
[ERROR] Step 'palantir-java-format' found problem in 'src/main/java/org/test/Test.java':
No enum constant javax.lang.model.element.Modifier.SEALED
java.lang.IllegalArgumentException: No enum constant javax.lang.model.element.Modifier.SEALED
    at java.lang.Enum.valueOf (Enum.java:240)
    at javax.lang.model.element.Modifier.valueOf (Modifier.java:47)
    at com.palantir.javaformat.java.ModifierOrderer.asModifier (ModifierOrderer.java:145)
    at com.palantir.javaformat.java.ModifierOrderer.reorderModifiers (ModifierOrderer.java:59)

```

### JDK 17

```
Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)
Java version: 17.0.6, vendor: Homebrew, runtime: /usr/local/Cellar/openjdk@17/17.0.6/libexec/openjdk.jdk/Contents/Home

...

[INFO] --- spotless:2.36.0:apply (default-cli) @ test ---
[INFO] Writing clean file: ..../src/main/java/org/test/Test.java
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Comment by kwin** [comment]
I also run into this issue, I guess this somehow is incorrectly parsed as [sealed class](https://openjdk.org/jeps/409), therefore at least Java 15 is required. Lower Java versions lead to that error. According to https://github.com/diffplug/spotless/blob/f6da1c494e818bb0a6279e2db512e0bc874b1c2a/lib/src/main/java/com/diffplug/spotless/java/PalantirJavaFormatStep.java#L32 the palantir-formatter in release 2.28.0 should fully support Java 11, however this version leads to this error.

Here is the full stack trace when executed with palantir-formatter 2.28.0 and spotless-maven-plugin 2.44.3

```
Caused by: java.lang.IllegalArgumentException: No enum constant javax.lang.model.element.Modifier.SEALED
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at java.compiler@11.0.26/javax.lang.model.element.Modifier.valueOf(Modifier.java:47)
	at com.palantir.javaformat.java.ModifierOrderer.asModifier(ModifierOrderer.java:145)
	at com.palantir.javaformat.java.ModifierOrderer.reorderModifiers(ModifierOrderer.java:59)
	at com.palantir.javaformat.java.Formatter.getFormatReplacements(Formatter.java:302)
	at com.palantir.javaformat.java.Formatter.formatSource(Formatter.java:284)
	at com.palantir.javaformat.java.Formatter.formatSource(Formatter.java:252)
	at com.diffplug.spotless.glue.pjf.PalantirJavaFormatFormatterFunc.apply(PalantirJavaFormatFormatterFunc.java:55)
	at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:33)
	at com.diffplug.spotless.Jvm$Support$1.apply(Jvm.java:209)
	... 35 more
```

**Comment by kwin** [comment]
Probably https://github.com/palantir/palantir-java-format/blob/dd02940abda1abe91a824b7ca06d49c3539e5e47/palantir-java-format/src/main/java/com/palantir/javaformat/java/ModifierOrderer.java#L146 needs to be conditional (depending on the current Java version).

**Comment by kwin** [comment]
I created https://github.com/google/google-java-format/issues/1224 to track this in the Google Java Formatter as the support of sealed classes has been backported from there.
