### ISSUE TITLE
Java 21 / JEP 441:  Pattern Matching for switch result in com.palantir.javaformat.java.FormatterException

### ISSUE THREAD

**Issue by matsev** [palantir/palantir-java-format#952]
Java 21 / [JEP 441 : Pattern Matching for switch](https://openjdk.org/jeps/441) code result in `com.palantir.javaformat.java.FormatterException`

## What happened?

This method compiles using JDK 21:

```java
class Example {
    static String test(CharSequence charSequence) {
        return switch (charSequence) {
            case String s when s.isEmpty() -> "empty string";
            case String s -> "non-empty string";
            default -> "not a String";
        };
    }
}
```

However, when using the `spotless-maven-plugin` together with `<palantirJavaFormat>`  results in an exception:
```bash
mvn spotless:apply
[...]
Unable to format file [path to Example.java]: com.palantir.javaformat.java.FormatterException: error: expected token: 'when'; generated - instead -> [Help 1]

```

Maven config:
```xml
                <plugin>
                    <groupId>com.diffplug.spotless</groupId>
                    <artifactId>spotless-maven-plugin</artifactId>
                    <version>2.40.0</version>
                    <configuration>
                        <java>
                            <palantirJavaFormat>
                                <version>2.38.0</version>
                            </palantirJavaFormat>
                        </java>
                    </configuration>
                </plugin>
```

Maven:
```bash
mvn -v
Apache Maven 3.9.5 (57804ffe001d7215b5e7bcb531cf83df38f93546)
Java version: 21, vendor: Amazon.com Inc.
Default locale: en_GB, platform encoding: UTF-8
OS name: "mac os x", version: "13.6.1", arch: "x86_64", family: "mac"
```

## What did you want to happen?

The `maven-spotless-plugin` and `palanter-java-format` should accept or reformat code that is supported by JDK 21

**Comment by koppor** [comment]
Can you manage to compile and try https://github.com/palantir/palantir-java-format/pull/935?

**Comment by matsev** [comment]
I have checked out PR #935 locally and I manage to build it if I use JDK 17 when running Cradle. 

```bash
./gradlew -v

------------------------------------------------------------
Gradle 7.6.2
------------------------------------------------------------

Build time:   2023-06-30 15:42:51 UTC
Revision:     dab132169006b16e7ada4ab2456e0c9d6415b52a

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.8 (Amazon.com Inc. 17.0.8+7-LTS)
OS:           Mac OS X 13.6.1 x86_64
```

```bash
./gradlew build
[...]
BUILD SUCCESSFUL in 29s
93 actionable tasks: 56 executed, 25 from cache, 12 up-to-date
```


However, that PR fails when tried to build using JDK 21 as it is not supported for running Gradle according to its [compatibility matrix](https://docs.gradle.org/current/userguide/compatibility.html):

```bash
./gradlew -v

------------------------------------------------------------
Gradle 7.6.2
------------------------------------------------------------

Build time:   2023-06-30 15:42:51 UTC
Revision:     dab132169006b16e7ada4ab2456e0c9d6415b52a

Kotlin:       1.7.10
Groovy:       3.0.13
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          21 (Amazon.com Inc. 21+35-LTS)
OS:           Mac OS X 13.6.1 x86_64
```
```bash
./gradlew build
[...]
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gradle-palantir-java-format:compileGroovy'.
> Unrecoverable compilation error: startup failed:
  General error during conversion: Unsupported class file major version 65
```

**Comment by mandrean** [comment]
Bump:

Java 21 is now supported from Gradle ~8.4 @matsev 

![image](https://github.com/palantir/palantir-java-format/assets/4631744/12d7e8ad-878a-4dbd-a6fa-85df10add982)

**Comment by matsev** [comment]
@mandrean Thanks for the notification. I made an attempt to upgrade the Gradle wrapper to use Gradle ver 8.5, but there is some more work required to make this work, please see #977 for details

**Comment by thijmenketel** [comment]
Any progress on this? We're starting to use more JDK21 features and this is preventing us to use `when`.

**Comment by piotrooo** [comment]
:+1: urgent and necessary

**Comment by rohan-changejar** [comment]
Any update on this, we have moved to java 21 and using the new switch case features seem impossible without this change

**Comment by talios** [comment]
Do you happen to have any updates on this issue? Is there anything specific holding it up that we can do to help resolve this?

Java 23 is just around the corner now, and I fear the lack of support for some of these newer constructs will become more and more of a problem for adoption (of both `palantir-java-format` and modern java itself).

**Comment by shollander** [comment]
google-java-format, on which this project is based, has supported Java 21 features for over 9 months: https://github.com/google/google-java-format/releases/tag/v1.19.0.

This project does not appear to be well maintained.

**Comment by carlmolemans** [comment]
@matsev Any progress on this? We were forced to rely on the google java format.

**Comment by CRogers** [comment]
We're now actively working on 21 support.

For context, we discovered a number of JDK 21 bugs that has made rolling services onto JDK 21 runtime difficult. Particularly for arm64 on linux, which we are some of the heaviest users, including some miscompilations from bytecode to native code (!!) that resulted in serious issues. We're over that hump now with virtually all our services on 21 runtime, so are now in position to start moving code to use source level 21 internally, so are going to build out support in the formatter.

We're evaluating moving to using a graal native-image version of the formatter to make upgrading easier. This is actually likely the bulk of the work.

* Currently, to use 21 source features with the formatter you'd need to ensure that both your Gradle daemon (for spotless) and IntelliJ use a 21 JDK. Providing a graal native-image should make distribution of the formatter much easier and not require these upgrades, especially as:
  * There's [yet another bug/behaviour change with Java 21 to do with environment variables for processes on macos](https://github.com/gradle/gradle/issues/10483#issuecomment-2507620705) that is temporarily stopping us moving to 21 for the Gradle daemon until we find a workaround.
  * We don't control the version of Java that various versions of IntelliJ uses, which makes it tricky to roll this out for our devs without manual action or some threading of an installed JDK to the IntelliJ plugin. 
* It also means that we should be able to ship preview/non-LTS changes in the formatter earlier.
* Finally, there's a serious performance problem with the current setup where in IntelliJ [we spin up new JDKs every time you format to ensure that the correct JVM `--add-exports` args](https://github.com/palantir/palantir-java-format/blob/faf7a32ee5f17f7a9e4ab08a3881820fdb7b1aef/idea-plugin/src/main/java/com/palantir/javaformat/intellij/FormatterProvider.java#L80-L87), which is very slow, especially when formatting lots of files from inside IntelliJ (eg after an automated refactor). From our benchmarking, starting a native-image process is >10x faster, and means don't need to manage the lifecycle of a long running separate process or require manual action to change the JDK args of IntelliJ itself.

**Comment by matsev** [comment]
@carlmolemans I am sorry, I am not a maintainer of this repo. I filed this issue some time ago and I also made some initial minor efforts to get the ball in motion. I have subscribed to PR #935 as some progress has been shared in the comments, but not as elaborate as @CRogers' [comment above](#issuecomment-2575750610).

@CRogers thanks for the update.

**Comment by talios** [comment]
> so are now in position to start moving code to use source level 21 internally,

@CRogers does that mean even if NOT using 21 source features or higher, the build will still need to run _from_ a 21+ JDK?

With the (potential) change to using native, does that mean any integration tools will just need to shell out to the formatter process, rather than call an API?  ( spotless, or other build tool integration).

Great to see work on this finally.  Cheers for a great formatter.

**Comment by CRogers** [comment]
> @CRogers does that mean even if NOT using 21 source features or higher, the build will still need to run from a 21+ JDK?

With the current formatter distribution setup, if you want to use source level X, you need to run the Gradle daemon (that spotless runs in) with a JDK >=X. The change to native means this is no longer the case, you can run the build with whatever JDK you want (although the Gradle plugin itself will have some minimum JDK requirement). Fwiw, Gradle 9 will require 17 daemon anyway.

> With the (potential) change to using native, does that mean any integration tools will just need to shell out to the formatter process, rather than call an API? ( spotless, or other build tool integration).

Yes, although the spotless step is defined in this repo, so we'll update it. Similarly for the intellij plugin. If someone else has made a custom integration they'll need to update it too (although we'll likely still ship the jar for the formatter so maybe it'll continue to work).

**Comment by talios** [comment]
Right, that all sounds like a larger ecosystem reason - using spotless, and gradle.   I'm currently using the spotless maven plugin, but also looking at writing support for https://github.com/rife2/bld .

**Comment by jvissers** [comment]
Great to see movement on the palantir project @CRogers! Does this also mean that you guys are working on issues like having '_' aka, enhanced underscore usage.

**Comment by koppor** [comment]
> google-java-format, on which this project is based, has supported Java 21 features for over 9 months: [google/google-java-format@`v1.19.0` (release)](https://github.com/google/google-java-format/releases/tag/v1.19.0).

Minor comment: GJF does not support Java 23: https://github.com/google/google-java-format/issues/1213

**Comment by wi11dey** [comment]
unsure if this is the same root cause but more complicated Java 21+ record destructuring also currently fails:
```
        return switch (new Adjacent(first, second)) {
            case Adjacent(Lock _lock, Unlock _unlock) -> null;
            case Adjacent(Lock lock, Value<?> _value) -> lock;
            case Adjacent(Lock _oldLock, Lock lock) -> lock;
            case Adjacent(Value<?> _value, Lock lock) -> lock;
            case Adjacent(Value<?> _oldValue, Value<?> value) -> value;
            case Adjacent(Value<?> _value, Unlock unlock) -> unlock;
            case Adjacent(Unlock _oldUnlock, Unlock unlock) -> unlock;
            case Adjacent(Unlock _unlock, Value<?> value) -> value;
            case Adjacent(Unlock _unlock, Lock lock) -> lock;
        };
```
with
```
21:32: error: ')' expected
com.palantir.javaformat.java.FormatterException: 21:32: error: ')' expected
	at com.palantir.javaformat.java.FormatterExceptions.fromJavacDiagnostics(FormatterExceptions.java:28)
	at com.palantir.javaformat.java.Formatter.parseJcCompilationUnit(Formatter.java:199)
	at com.palantir.javaformat.java.RemoveUnusedImports.parse(RemoveUnusedImports.java:214)
	at com.palantir.javaformat.java.RemoveUnusedImports.removeUnusedImports(RemoveUnusedImports.java:202)
	at com.palantir.javaformat.java.Formatter.formatSourceAndFixImports(Formatter.java:261)
	at com.palantir.javaformat.java.FormatterServiceImpl.formatSourceReflowStringsAndFixImports(FormatterServiceImpl.java:43)
	at com.diffplug.spotless.FormatterFunc.apply(FormatterFunc.java:32)
	at com.diffplug.spotless.FormatterStepImpl$Standard.format(FormatterStepImpl.java:82)
	at com.diffplug.spotless.FormatterStep$Strict.format(FormatterStep.java:88)
	at com.diffplug.spotless.Formatter.compute(Formatter.java:230)
	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:203)
	at com.diffplug.spotless.PaddedCell.calculateDirtyState(PaddedCell.java:190)
	at com.diffplug.gradle.spotless.SpotlessTaskImpl.processInputFile(SpotlessTaskImpl.java:92)
	at com.diffplug.gradle.spotless.SpotlessTaskImpl.performAction(SpotlessTaskImpl.java:78)
	at java.base@17.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@17.0.14/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base@17.0.14/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
```

**Comment by crogoz** [comment]
We have released a new version of palantir-java-format with compatibility for Java 21 source -https://github.com/palantir/palantir-java-format/pull/1211. Versions  `>= 2.57.0` add support for JEP-441 Pattern Matching switch (with guard) and JEP-443 Unnamed Patterns and Variables

**Comment by bmarwell** [comment]
https://github.com/palantir/palantir-java-format/issues/930 is still open 😢

I don't consider this PR "full Java 21 support", text blocks were introduced in Java 14. 😐

**Comment by punya** [comment]
I believe record pattern support is still incomplete: https://github.com/palantir/palantir-java-format/issues/1309

**Comment by vzorge** [comment]
This seems to be fixed as per this comment: https://github.com/palantir/palantir-java-format/issues/1101#issuecomment-2721609483
